apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-prometheus-grafana
  namespace: monitoring
  labels:
    app: prometheus-grafana
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 5Gi
  volumeName: pv-prometheus-grafana
